# Generated by Django 3.2.25 on 2024-12-23 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='brand',
            fields=[
                ('brand_id', models.AutoField(primary_key=True, serialize=False)),
                ('brand_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Colour',
            fields=[
                ('colour_id', models.AutoField(primary_key=True, serialize=False)),
                ('colour_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=255)),
                ('product_description', models.TextField()),
                ('model_height', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('model_wearing', models.CharField(blank=True, max_length=255, null=True)),
                ('care_instructions', models.TextField(blank=True, null=True)),
                ('about', models.TextField(blank=True, null=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='app.brand')),
            ],
        ),
        migrations.CreateModel(
            name='SizeCategory',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SizeOption',
            fields=[
                ('size_id', models.AutoField(primary_key=True, serialize=False)),
                ('size_name', models.CharField(max_length=255)),
                ('sort_order', models.IntegerField()),
                ('size_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.sizecategory')),
            ],
        ),
        migrations.CreateModel(
            name='ProductItem',
            fields=[
                ('product_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_code', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', models.CharField(blank=True, max_length=100, null=True)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('colour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_items', to='app.colour')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='app.product')),
            ],
        ),
        migrations.CreateModel(
            name='product_category',
            fields=[
                ('product_category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=100)),
                ('category_description', models.CharField(max_length=100)),
                ('category_image', models.ImageField(upload_to='product_category')),
                ('parent_category_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategories', to='app.product_category')),
                ('size_category_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='size_categories', to='app.product_category')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='product_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='app.product_category'),
        ),
    ]
