# Generated by Django 3.2.25 on 2025-01-03 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_address_address_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_category',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='productitem',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True),
        ),
    ]
