# Generated by Django 3.2.25 on 2025-01-03 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20250103_0834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productitem',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
