# Generated by Django 3.2.25 on 2025-01-03 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_productitem_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='productitem',
            name='size_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.sizecategory'),
        ),
        migrations.AlterField(
            model_name='productitem',
            name='colour',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.colour'),
        ),
    ]
