# Generated by Django 3.2.25 on 2025-01-03 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20250103_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_category',
            name='category_image',
            field=models.ImageField(blank=True, null=True, upload_to='product_category'),
        ),
    ]
