# Generated by Django 3.2.25 on 2025-01-06 10:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0007_alter_product_category_category_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersmodel',
            name='user_id',
        ),
        migrations.AddField(
            model_name='usersmodel',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user'),
            preserve_default=False,
        ),
    ]
