# Generated by Django 3.2.25 on 2025-01-06 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20250106_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='sizeoption',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
