# Generated by Django 3.2.25 on 2025-01-08 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_sizeoption_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='productitem',
            name='size_options',
            field=models.ManyToManyField(to='app.SizeOption'),
        ),
    ]
