# Generated by Django 3.2.25 on 2025-01-08 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_productitem_size_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVariation',
            fields=[
                ('variation_id', models.AutoField(primary_key=True, serialize=False)),
                ('qty_in_stock', models.PositiveIntegerField()),
                ('product_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.productitem')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.sizeoption')),
            ],
        ),
    ]
