# Generated by Django 3.2.25 on 2025-01-08 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_productvariation'),
    ]

    operations = [
        migrations.AddField(
            model_name='sizeoption',
            name='qty_in_stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
